USE CGV;
-- 예매한 영화이름, 영화관, 좌석이름, ID, 상영일, 상영시간을 조회하는 뷰
DROP VIEW TICKET_DETAIL1;
CREATE VIEW TICKET_DETAIL1
AS
SELECT MO_TITLE, SS_DATE, SS_TIME, CI_NAME, SE_NAME, TI_ME_ID 
	FROM ticketing
		JOIN TICKETING_SEAT ON TI_NUM = TS_TI_NUM
		JOIN SEAT ON SE_NUM = TS_SE_NUM
		JOIN screen_schedule ON SS_NUM = TI_SS_NUM
		JOIN MOVIE ON MO_NUM = SS_MO_NUM
		JOIN CINEMA ON CI_NUM = SS_CI_NUM;
        
DROP VIEW TICKET_DETAIL2;
CREATE VIEW TICKET_DETAIL2
AS
SELECT * FROM ticketing
		JOIN TICKETING_SEAT ON TI_NUM = TS_TI_NUM
		JOIN SEAT ON SE_NUM = TS_SE_NUM
		JOIN screen_schedule ON SS_NUM = TI_SS_NUM
		JOIN MOVIE ON MO_NUM = SS_MO_NUM
		JOIN CINEMA ON CI_NUM = SS_CI_NUM;
        
SELECT * FROM TICKET_DETAIL2;

-- ABC 회원이 영화예매를 위해 사용한 금액은?
SELECT SUM(SE_PRICE) AS `예매 금액` FROM TICKET_DETAIL2;